name: DEV1 Validation
on:
  pull_request:
    branches: [dev1]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'force-app/main/default/**'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: awareservices/sfdx-cli:latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SFDX Login
        run: echo ${{ secrets.AUTH_DEV1 }} > authFile && sfdx auth:sfdxurl:store -f authFile --setdefaultusername
      - run: rm authFile
      - name: SFDX Generate Delta Package
        run: export HOME=/root && sfdx sgd:source:delta --to "HEAD" --from "origin/dev1" --output "." --source force-app/main/default --ignore .forceignore
      - run: cat package/package.xml
      - name: SFDX Run Validation on added and modified metadata
        run: if grep -q '<types>' package/package.xml; then sfdx force:source:deploy -x package/package.xml --postdestructivechanges destructiveChanges/destructiveChanges.xml --checkonly; fi
