name: Change Set DEV1 > QA
on:
  workflow_dispatch:
    inputs:
      cs_name:
        description: 'Change Set Name'
        required: true
jobs:
  create_feature_branch:
    name: Create Feature Branch From Change Set
    runs-on: ubuntu-latest
    container:
      image: awareservices/sfdx-cli:latest
    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v2
        with:
          ref: qa
      - name: SFDX Login
        run: echo ${{ secrets.AUTH_DEV1 }} > authFile && sfdx auth:sfdxurl:store -f authFile --setdefaultusername
      - run: rm authFile
      - name: SFDX Retrieve Change Set Package
        run: sfdx force:source:retrieve -n "${{ github.event.inputs.cs_name }}"
      - name: Merge package into force-app directory
        run: cp -r "${{ github.event.inputs.cs_name }}/main" "force-app"
      - name: Remove package directory
        run: rm -r "${{ github.event.inputs.cs_name }}"
      - name: Create branch name
        run: CS_NAME="${{ github.event.inputs.cs_name }}" && echo "branch_name=CS-${CS_NAME// /-}" >> $GITHUB_ENV
      - uses: EndBug/add-and-commit@v9
        with:
          message: '${{ github.event.inputs.cs_name }}'
          new_branch: ${{ env.branch_name }}
          push: 'origin ${{ env.branch_name }} --force'
